Samples/MobileBuyIntegration/MobileBuyIntegration/SettingsViewController.swift
=> Improve wording on settings screen

Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
=> Remove buy with prime intent

Sources/ShopifyCheckout/CheckoutBridge.swift
Adds standard variant token to User-Agent
=> Add standard variant token to User-Agent

Sources/ShopifyCheckout/CheckoutBridge.swift
=> Bump schema version to 5.3

README.md, Sources/ShopifyCheckout/ShopifyCheckout.swift
=> Bump version to 0.5.0

Samples/SwiftUIExample/Storefront.xcconfig, Samples/SwiftUIExample/Storefront.xcconfig.example
Fixes the config file in the sample 
---
=> fix storefront.xcconfig example in swift-ui sample

README.md, Samples/SimpleAppIntegration/SimpleAppIntegration.xcodeproj/xcshareddata/xcschemes/SimpleAppIntegration.xcscheme
=> fix typo in header

README.md
=> update preloading docs

Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.pbxproj, Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
The sample app cannot be built due to an error in the dependencies. This PR fixes it.
Open the sample app in Xcode and build it.
=> Update MobileBuyIntegration dependencies

README.md, Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift
Describes how to consume Web Pixel events.
---
=> Update Web Pixels documentation

CHANGELOG.md, README.md, ShopifyCheckoutSheetKit.podspec, Sources/ShopifyCheckoutSheetKit/PixelEvents.swift
- Add missing `Codable`
- Improve comments on types
---
=> [Patch 0.10.1] Fix PixelEvent types

README.md
Remove mentions of “Developer preview” from the README.
=> Remove mentions of “Developer preview”

CHANGELOG.md, ShopifyCheckoutSheetKit.podspec, Sources/ShopifyCheckoutSheetKit/ShopifyCheckoutSheetKit.swift
Bump version number in package
---
=> Bump version number in package

Samples/SwiftUIExample/SwiftUIExample/ContentView.swift, Samples/SwiftUIExample/SwiftUIExample/StorefrontClient.swift, Samples/SwiftUIExample/SwiftUIExample/StorefrontGraphQL.swift
Small improvements to SwiftUI sample app
---
> [!IMPORTANT]
> - [ ] I've updated any documentation related to these changes.
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](./CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the …
=> Improve SwiftUI sample app

README.md, Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.pbxproj, Samples/MobileBuyIntegration/MobileBuyIntegration/AppDelegate.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Localizable.xcstrings, Sources/ShopifyCheckoutSheetKit/CheckoutWebViewController.swift, Sources/ShopifyCheckoutSheetKit/Configuration.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutViewControllerTests.swift
<details>
<summary>Expand for video walkthrough</summary>
https://github.com/Shopify/checkout-sheet-kit-swift/assets/2034704/6fbd852a-fbfb-4749-ac09-9b1b386555a1
</details>
---
> [!IMPORTANT]
> - [ ] I've updated any documentation related to these changes.
---
<details>
</details>
> [!TIP]
> See …
=> Make title configurable

CHANGELOG.md, ShopifyCheckoutSheetKit.podspec
[1.0.2] Patch + add changelog entry
---
> [!IMPORTANT]
> - ~I've added tests to support my implementation~
> - ~I've updated the [README](https://github.com/shopify/checkout-sheet-kit-swift).~
---
> [!TIP]
=> [1.0.2] Patch + add changelog entry

Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/.allowed-script-phases.yml
Add an allowed script phases file, required by E2E tests.
n/a
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
=> add allowed script phases file

Samples/MobileBuyIntegration/MobileBuyIntegration/SettingsViewController.swift, Samples/SwiftUIExample/SwiftUIExample/App.swift, Samples/SwiftUIExample/SwiftUIExample/CatalogView.swift
---
> [!IMPORTANT]
> - ~I've added tests to support my implementation~
---
<details>
</details>
> [!TIP]
=> SwiftUI Previews

Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Localizable.xcstrings, Samples/SwiftUIExample/SwiftUIExample/CartView.swift, Sources/ShopifyCheckoutSheetKit/CheckoutBridge.swift, Sources/ShopifyCheckoutSheetKit/CheckoutCompletedEvent.swift, Sources/ShopifyCheckoutSheetKit/CheckoutCompletedEventDecoder.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutViewControllerTests.swift, Tests/ShopifyCheckoutSheetKitTests/SwiftUITests.swift
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
=> Make CheckoutCompleted event types stricter

ShopifyCheckoutSheetKit.podspec, Sources/ShopifyCheckoutSheetKit/CheckoutBridge.swift, Sources/ShopifyCheckoutSheetKit/Configuration.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift
Adds a "Platform" property to the ShopifyCheckoutSheetKit configuration for identifying other platforms.
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](./CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the …
=> Add "platform" configuration property

README.md, ShopifyCheckoutSheetKit.podspec, Sources/ShopifyCheckoutSheetKit/CheckoutBridge.swift, Sources/ShopifyCheckoutSheetKit/CheckoutError.swift, Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewTests.swift
Removes customer_account_required check
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
=> Remove customer_account_required check

.github/workflows/stale.yml
Remove duplicate key in workflow
Use stale label for PRs and issues
N.B. my IDE did some autoformatting, probably best to hide whitespace when reviewing
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/b …
=> Remove duplicate key in stale workflow

.github/workflows/stale.yml
Use stale label for stale PRs
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the library.
=> Use stale label for prs too

CHANGELOG.md, ShopifyCheckoutSheetKit.podspec, Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift, Sources/ShopifyCheckoutSheetKit/ShopifyCheckoutSheetKit.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewTests.swift
Potential fix for #203 
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the library.
=> Set allowsInlineMediaPlayback to true on webview

Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift
Adds quantity controls to the MobileBuyIntegration sample app
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to …
=> Add quantity controls to MobileBuyIntegration sample app

Samples/SwiftUIExample/SwiftUIExample/App.swift, Samples/SwiftUIExample/SwiftUIExample/CartView.swift, Samples/SwiftUIExample/SwiftUIExample/CatalogView.swift
Improvements to SwiftUI sample app
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the …
=> Improvements to SwiftUI sample app

CHANGELOG.md, ShopifyCheckoutSheetKit.podspec, Sources/ShopifyCheckoutSheetKit/ShopifyCheckoutSheetKit.swift
=> [Minor] 3.1.0

.vscode/extensions.json, README.md
Adds vscode recommendations + fixes hierarchy
=> Add vscode recommendations

README.md
Adding link to the guide on authentication with customer accounts to the readme
Doc update
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
=> Update readme with auth docs reference

README.md
The link for `/Samples` was broken (it was updated from `samples` -> to `Samples`). This PR updates the link.
The link should redirect to [Samples](https://github.com/Shopify/checkout-sheet-kit-swift/tree/main/Samples)
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing …
=> Update README link to "/Samples"

README.md
-Added cart permalink use case
-Added app developers must obtain proper levels of consent before collecting web pixel data
Fixes [#1063](https://github.com/Shopify/checkout-roadmap/issues/1063)
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing …
=> Update README CSK Swift for cart permalink use case.md

Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift, Samples/SwiftUIExample/SwiftUIExample/ProductViewModel.swift
Prevent bug where we attempt to deserialize user errors even when they are not requested
n/a
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
=> Request user errors

Scripts/lint, dev.yml
> The intention here is to have a `dev check` command which will run build-package / test / lint / format / build-samples - subsequent PR's will include additional scripts, build: https://github.com/Shopify/checkout-sheet-kit-swift/pull/311
Adds a script and dev command which runs swiftlint and swiftformat locally
The repo isn't currently guarding against swiftformat issues getting in, so running it will result in a lot of changes (see video below)
You can run either `dev lint` or `Scripts/lint` to check for errors
Run `dev fix` or `scripts/lint fix` to autofix any autofixable issues 
https://github.com/user-attachments/assets/efd92e75-3984-4e6a-a9a4-1064408c06bd
---
> [!IMPORTANT]
>
> - [ ] I have read and agree with the [Contribution …
=> chore: add lint script with fix and check actions

.github/dependabot.yaml
Update dependabot to include swift packages
n/a we can trigger after merge to verify
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
=> update dependabot to include swift packages

Samples/MobileBuyIntegration/MobileBuyIntegration/Localizable.xcstrings, Samples/MobileBuyIntegration/MobileBuyIntegration/SceneDelegate.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Views/CartView.swift
Renders a cart icon on the right of the navigation bar on the "Catalog" page. On click, this opens the `CartView` in a sheet and from there you can present checkout programmatically or via an instance of `CheckoutSheet`.
I'm making this change for the following reasons:
1. It enables us to dogfood both implementations and encourages us to continually test both.
2. It enables us to test sheets triggered from sheets.
|Catalog|Cart Sheet|Checkout Sheet|
|-------|----------|----------|
|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-07-15 at 16 01 34" src="https://github.com/user-attachments/assets/cc7a342c-8e76-4e32-9414-c6c7f6fa34d6" />|<img width="1320" height="2868" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-07-15 at 16 01 47" …
=> [Sample app improvements] Render cart in sheet + render an instance of CheckoutSheet

Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/PKEncoderTests.swift
I forgot to push the tests I was working on before merging https://github.com/Shopify/checkout-sheet-kit-swift/pull/353
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md# …
=> Add billingContact tests for PKEncoder

Package.swift, ShopifyCheckoutSheetKit.podspec, Sources/Common/MetaData.swift, Sources/Common/UserAgent.swift, Sources/ShopifyAcceleratedCheckouts/Internal/GraphQLClient/GraphQLClient.swift, Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayViewController.swift, Sources/ShopifyAcceleratedCheckouts/Wallets/ShopPay/ShopPayViewController.swift, Sources/ShopifyCheckoutSheetKit/CheckoutBridge.swift, Sources/ShopifyCheckoutSheetKit/CheckoutViewController.swift, Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift, Sources/ShopifyCheckoutSheetKit/CheckoutWebViewController.swift, Sources/ShopifyCheckoutSheetKit/Configuration.swift, Sources/ShopifyCheckoutSheetKit/ShopifyCheckoutSheetKit.swift, Tests/CommonTests/UserAgentTests.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift, Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewControllerTests.swift
Adds in a new present method that is package scoped so that it isn't expanding our public API, and is only used by the `ShopifyAcceleratedCheckouts` package.
This allows us to append a new property to the end of the user agent.
After discussions with Mark we decided not to add this as a labeled property in the parameters section of the useragent to avoid being a backwards incompatible change and requiring changes in checkout-web / core to get this done.
- Open the `ShopPayViewController.swift`
- Run the sample app, create any cart and press the shop pay button
- You should see AcceleratedCheckouts is appended to the end of the user agent
- Comment out the 3rd position argument "entryPoint" in the `ShopifyCheckoutSheetKit.present` call
- You should see the old user agent is preserved …
=> [AC][CSK]: Add UserAgent to AC requests, update CSK UserAgent **only** when launched from AC

Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.pbxproj, Samples/MobileBuyIntegration/MobileBuyIntegration/AppConfiguration.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Localizable.xcstrings, Samples/MobileBuyIntegration/MobileBuyIntegration/SceneDelegate.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/ViewControllers/CartViewController.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Views/CartView.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Views/ProductGridView.swift, Samples/MobileBuyIntegration/MobileBuyIntegration/Views/ProductView.swift, Sources/Common/Theme.swift, Sources/ShopifyAcceleratedCheckouts/Internal/AcceleratedCheckoutButton.swift, Sources/ShopifyAcceleratedCheckouts/Internal/AcceleratedCheckoutConfigurable.swift, Sources/ShopifyAcceleratedCheckouts/Internal/AcceleratedCheckoutDelegate.swift, Sources/ShopifyAcceleratedCheckouts/Internal/AcceleratedCheckoutDelegateWrapper.swift, Sources/ShopifyAcceleratedCheckouts/Internal/Controllers/AcceleratedCheckoutViewController.swift, Sources/ShopifyAcceleratedCheckouts/ShopifyAcceleratedCheckouts.swift, Sources/ShopifyAcceleratedCheckouts/Wallets/AcceleratedCheckoutButtons.swift, Sources/ShopifyAcceleratedCheckouts/Wallets/ShopPay/ShopPayViewController.swift, Tests/ShopifyAcceleratedCheckoutsTests/AcceleratedCheckoutViewControllerTests.swift
Integrates AcceleratedCheckouts in MobileBuyIntegration sample app.
**Note, this depends on:**
- #358 
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-v …
=> [Sample] Integrate AcceleratedCheckouts in MobileBuyIntegration sample app

README.md
Update readme to reflect Checkout Kit rename
=> Update README.md text for Checkout Kit rename

Sources/ShopifyAcceleratedCheckouts/Internal/GraphQLClient/GraphQLDocument/GraphQLDocument+Mutations.swift, Sources/ShopifyAcceleratedCheckouts/Internal/GraphQLClient/GraphQLRequest/GraphQLRequest+Operations.swift, Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI+Mutations.swift, Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI+Types.swift, Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate+Controller.swift, Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate.swift, Tests/ShopifyAcceleratedCheckoutsTests/Internal/GraphQLClient/GraphQLClientTests.swift, Tests/ShopifyAcceleratedCheckoutsTests/Internal/StorefrontAPI/StorefrontAPIMutationsTests.swift, Tests/ShopifyAcceleratedCheckoutsTests/TestHelpers.swift, Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegateControllerTests.swift
The following changes fix issues with updating addresses across countries.
- `cartDeliveryAddressesAdd` Open Apple Pay sheet with default Address A (no taxes collected for this country) ← First set of delivery rates returned
- `cartDeliveryAddressesUpdate` Change to North American address ← taxes collected, new set of delivery rates returned
- `cartDeliveryAddressesUpdate` Change back to original address ← No delivery rates returned
- `cartDeliveryAddressesAdd` Open Apple Pay sheet with default Address A (no taxes collected for this country) ← First set of delivery rates returned
- `cartDeliveryAddressesRemove + cartDeliveryAddressesAdd` Change to North American address ← taxes collected, new set of delivery rates returned
- `cartDeliveryAddressesRemove + cartDeliveryAddressesAdd` Change …
=> Fix for cart addresses update

Scripts/lint
SwiftLint doesn't exit 0 / print errors in `--fix` mode
They recommend re-running in `--strict` after if you want to see violation https://github.com/realm/SwiftLint?tab=readme-ov-file#additional-considerations 
Before:
After:
`dev fix`
`dev style`
---
> [!IMPORTANT]
>
---
<details>
</details>
> …
=> [dev.yml]: Print errors requiring manual intervention during `dev fix` 

dev.yml
Fix dev.yml format, but nesting `packages` under `up`
> [!IMPORTANT]
>
>
>
> - [ ] I have added a …
=> Move packages under up

Sources/ShopifyAcceleratedCheckouts/Localizable.xcstrings
Prunes unrelated translation keys for Accelerated Checkouts. More languages will be added in a subsequent PR.
---
> [!IMPORTANT]
>
>
>
>
> _Releasing a new …
=> Prune unused translation keys

Samples/MobileBuyIntegration/MobileBuyIntegration/Views/CartView.swift
Stops the sheet from closing on completion.
---
> [!IMPORTANT]
>
>
>
>
> _Releasing a new major version?_
>
> - [ ] I have bumped the version number in the …
=> [Sample] Stop closing sheet on completion

Sources/ShopifyAcceleratedCheckouts/Localizable.xcstrings
Note: it is best to review this PR commit by commit.
All locales with the exception of English are missing the following 3 translations:
---
> [!IMPORTANT]
>
>
>
> - [ ] I have bumped the version number in the [`podspec` file](https://github.com/Shopify/checkout-sheet-kit-swift/blob/main/ShopifyCheckoutKit.podspec#L …
=> More locales for Accelerated Checkouts
