Shopify/checkout-sheet-kit-swift

- README.md
Xcode 15 seems to have introduced new setting names
> fix: README install steps

- Samples/MobileBuyIntegration/MobileBuyIntegration/SettingsViewController.swift
Removes the white tint in the "web_browser" setting to avoid rendering the keyboard action icons in white.
> Remove white tint in web setting

- Samples/MobileBuyIntegration/MobileBuyIntegration/SettingsViewController.swift
- Sources/ShopifyCheckout/CheckoutViewController.swift
Updates the colors for the `web_default`  setting in the sample app
> Update web colors for sample app

- README.md
- Samples/MobileBuyIntegration/MobileBuyIntegration/SettingsViewController.swift
- Sources/ShopifyCheckout/CheckoutViewController.swift
- Sources/ShopifyCheckout/Configuration.swift
Allows the configuration of the webview background color
> Add backgroundColor to configuration

- Sources/ShopifyCheckout/CheckoutViewController.swift
Originally added in this [PR](https://github.com/Shopify/mobile-checkout-sdk-ios/pull/19/files#diff-89a8f78eb54bfa9e91c749dc0df96af5ca838a629633b67b01132790a94956eaR109)
The problem we were originally looking to solve was this:
> If we enable by default but never the client never calls preload, the first time checkout is loaded will be when the user clicks the checkout button. However, it will still be cached. So imagine the user goes back to add something to their cart.. Their checkout will not be refreshed. clears the cache by calling preload.
Testing this, the result is I can complete checkout but I’m missing my added cart items (the price doesn’t change from the first iteration)
We could prevent caching until preload is called at least once.
tl;dr we wanted to ensure preload was …
> don't invalidate preloaded cache on checkout close events

- Sources/ShopifyCheckout/CheckoutViewController.swift
Fix the error that happens if fixing the Pay Button to the bottom of the page. 
IOS allows the user to scroll past the bottom 0, which breaks the fixed position of the button.
Bug:
https://github.com/Shopify/mobile-checkout-sdk-ios/assets/1781007/e6a9c08f-d28b-4584-bf4e-328b5830dd00
`checkoutView.scrollView.contentInsetAdjustmentBehavior = .never`
Removing the inset auto adjustment from the view helps, but breaks the header.
https://github.com/Shopify/mobile-checkout-sdk-ios/assets/1781007/7e169a62-d896-4ae6-b5e0-967d60b89b6b
Anchoring the top of the webview to the safe area solves this issue
`checkoutView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor)`
https://github.com/Shopify/mobile-checkout-sdk-ios/assets/1781007/717286d5-40e1-44bd-becb-c3435aab2f70
No negative …
> Prevent webview from scrolling past the bottom 0 limit

- Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Samples/MobileBuyIntegration/MobileBuyIntegration/SettingsViewController.swift
Fix memory leak by reloading the logs on the main thread each time the settings view renders
> Fix memory leak in sample app

- CHANGELOG.md
- README.md
- ShopifyCheckoutKit.podspec
- Sources/ShopifyCheckoutKit/CheckoutBridge.swift
- Sources/ShopifyCheckoutKit/CheckoutViewController.swift
- Sources/ShopifyCheckoutKit/CheckoutWebView.swift
- Sources/ShopifyCheckoutKit/CheckoutWebViewController.swift
- Sources/ShopifyCheckoutKit/ShopifyCheckoutKit.swift
- Tests/ShopifyCheckoutKitTests/CheckoutBridgeTests.swift
- Tests/ShopifyCheckoutKitTests/CheckoutWebViewTests.swift
- Tests/ShopifyCheckoutKitTests/Mocks/MockWebView.swift
Emit a presented event from the SDK to checkout when the sheet is raised.  This will help with analytics.
> emit presented event to distinguish between preloads and presented checkouts

- Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.pbxproj
- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/CountryCode+inferRegion.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/ProductViewController.swift
Specify countryCode in queries/mutations to prevent switching in checkout. This will prevent the banner being shown when checkout is presented.
---
> Specify countryCode in queries/mutations to prevent switching in checkout

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
Updates the sample app to use the buyer identity countryCode for mutations, when checkout is being prefilled. This prevents the shipping address banner from appearing.
> Use buyer identity country in vaulted state

- Sources/ShopifyCheckoutSheetKit/PixelEvents.swift
Make Pixel Event fields public.
> Make Pixel Event fields public

- Sources/ShopifyCheckoutSheetKit/CheckoutWebViewController.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutViewControllerTests.swift
Fixes an issue where the loading spinner is presented again when redirecting to Shop Pay.
---
> Only animate loader if checkout hasn't already loaded

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift
Add support for custom events
---
> [Sample] Add support for custom events

- Sources/ShopifyCheckoutSheetKit/CheckoutBridge.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutCompletedEvent.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutDelegate.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift
- Tests/ShopifyCheckoutSheetKitTests/Mocks/MockLogger.swift
I have verified the following events:
---
> [!IMPORTANT]
> - [ ] I've updated any documentation related to these changes.
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](./CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the …
> Update schema from 7.0 to 8.0

- Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift
- Sources/ShopifyCheckoutSheetKit/MessageHandler.swift
We are retaining `WKScriptMessageHandler`s in some cases (e.g. when a checkout completes, and is closed). As our script handler is `CheckoutWebView` this is causing the WebView itself to be retained, and leak.
This adds a wrapper class which uses a weak ref to the CheckoutWebView, allowing it to be cleared up. Based on this:
https://stackoverflow.com/questions/26383031/wkwebview-causes-my-view-controller-to-leak/26383032#26383032
On main:
1. Run the sample app.
2. Open checkout
3. Check in Safari dev tools for the # of inspectable WebViews (it should be 1)
4. Complete checkout
5. Close checkout 
6. Begin a new checkout
7. Check in Safari dev tools for the # of inspectable WebViews (it should be 1, but is 2)
Repeat on this branch, and check that the count is now 1 in step 7.
> [!IMPORTANT] …
> Prevent retaining the scripthandler / webview

- .prettierrc.json
- README.md
- ShopifyCheckoutSheetKit.podspec
- Sources/ShopifyCheckoutSheetKit/ShopifyCheckoutSheetKit.swift
- Updates the README to give guidance to the graceful recovery implementation.
- Bumps the version from `2.0.1` → `3.0.0-beta.1`
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](./CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish …
> [3.0.0-beta.1] Version bump + readme improvements

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift
- ShopifyCheckoutSheetKit.podspec
- Sources/ShopifyCheckoutSheetKit/CheckoutWebViewController.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutViewControllerTests.swift
Dismisses the sheet when an unrecoverable error is encountered.
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
> Dismiss sheet by default on unrecoverable error

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift
- ShopifyCheckoutSheetKit.podspec
- Sources/ShopifyCheckoutSheetKit/CheckoutBridge.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutError.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift
Removes redundant AuthenticationError
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
> Remove AuthenticationError

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/Info.plist
- Samples/MobileBuyIntegration/Storefront.xcconfig.example
Wires up the "PHONE" field from `Storefront.xcconfig` in the MobileBuyIntegration sample app.
---
> [!IMPORTANT]
---
<details>
</details>
> [!TIP]
> Wire up phone field in MobileBuyIntegration sample app

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/CartViewController.swift
- Samples/SwiftUIExample/SwiftUIExample/CartView.swift
- Samples/SwiftUIExample/SwiftUIExample/ProductViewModel.swift
Preload should not be called on each cart mutation, but instead when we have a strong signal that a user will enter checkout see [preloading considerations](https://github.com/Shopify/checkout-sheet-kit-swift?tab=readme-ov-file#additional-considerations-for-preloaded-checkout).
Update the sample app to show something more appropriate.
N.B. this could be improved to not call preload() if cart is reopened and there have been no changes to the cart
---
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of Conduct](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.gi …
> Call preload when opening cart

- Samples/SwiftUIExample/SwiftUIExample/CartView.swift
- Samples/SwiftUIExample/SwiftUIExample/ProductViewModel.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift
- Sources/ShopifyCheckoutSheetKit/ShopifyCheckoutSheetKit.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewTests.swift
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the library.
> Expose "invalidate" function, update SwiftUI sample

- README.md
- Sources/ShopifyCheckoutSheetKit/CheckoutURL.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebViewController.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutURLTests.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutViewControllerTests.swift
Multipass URLs contain one-time tokens which cannot be re-used. When the kit "recovers" these URLs, the webview will receive a 422 Unprocessable Entity error.
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-s …
> Prevent recovery for multipass URLs

- Sources/ShopifyCheckoutSheetKit/CheckoutURL.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutURLTests.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewTests.swift
Based on #226 - this PR includes deep links in calls to `checkoutDidClickLink`
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
> Open deep links externally

- Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.pbxproj
- Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Ensures `.pcm` and `Swiftlint` binaries are not included in archived builds when uploading to AppStoreConnect.
---
> [!IMPORTANT]
>
> Remove binaries from archived build

- Samples/MobileBuyIntegration/MobileBuyIntegration/ApplePay/ApplePayHandler.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/ApplePay/PassKitFactory.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/StorefrontClient.swift
The following was reported by a merchant: 
> When the user is signed out, we don’t have their email address. 
> However, Apple Pay cannot be completed successfully without updating the buyerIdentity email address. 
> Even if we ask for the email as a required field during shipping or billing, Apple will only provide it after authentication is successful. 
> What do you suggest as the best way forward in this scenario?
There are two changes, for two issues essentially.
1. Email address always uses vaulted value (feature toggle doesn't change this)
This wasn't caught during initial development due to a bug causing vaulted information to always be used in the mutation for buyer identity, regardless of the featureflag in settings.
This PR fixes that and ensures we only use vaulted email if …
> Fix buyer identity email address violation for guest (non-vaulted) users

- Samples/MobileBuyIntegration/MobileBuyIntegration/ApplePay/ApplePayHandler.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/ApplePay/PassKitFactory.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/StorefrontClient.swift
The buyerIdentityUpdate was failing with userErrors due to an empty email being submitted, this didn't fail the flow so wasn't picked up before but it does prevent the shipping methods showing
The API expects a nil value if the email isn't available yet, so making it optional fixes this
I also included a fix to a log that was coming out in this case with the delivery groups being empty, technically this is fine as for digital products there won't be shipping methods
---
> [!IMPORTANT]
>
> - [ ] I have read and agree with the [Code of …
> fix: buyerIdentityUpdate failing from empty email

- Sources/ShopifyCheckoutSheetKit/PixelEvents.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift
Add `checkout.order.customer.isFirstOrder` attribute to checkout pixel events
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on …
> add isFirstOrder to pixel events order.customer

- .swiftformat
- Sources/ShopifyCheckoutSheetKit/CheckoutCompletedEvent.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutDelegate.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutViewController.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebView.swift
- Sources/ShopifyCheckoutSheetKit/Configuration.swift
We would prefer that the access control be closer to the declaration and less "implicit" / transient.
Reversing this rule undoes the changes made in https://github.com/Shopify/checkout-sheet-kit-swift/pull/320 to format the files 
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the …
> Reverse rule on extension access control modifiers

- Sources/ShopifyAcceleratedCheckouts/Wallets/ShopPay/ShopPayViewController.swift
We are dismissing the sheet after every onComplete event which means we never view the TYP
- Open Shop Pay
- Complete checkout (any way you prefer, doesn't matter)
- Sheet closes before TYP
❌ Old Behaviour
https://github.com/user-attachments/assets/c430cab5-8a3a-40ab-9517-e183367b4560
✅ After
https://github.com/user-attachments/assets/f9ebeaae-43d6-4ac3-bc15-fff10d160a45
---
> [!IMPORTANT]
>
> - [ ] I've updated the …
> [AC][ShopPay]: Ensure Thank You Page is displayed after successful checkout

- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp/Views/CartBuilderView.swift
- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp/Views/Components/ButtonSet.swift
This specifically affects the cartID version of the buttons.
The cart can only be used for checkout once, and we don't have a means to clone the cart at the moment. 
So after an onComplete we should clear out the cart state as per [docs](https://github.com/Shopify/checkout-sheet-kit-swift?tab=readme-ov-file#monitoring-the-lifecycle-of-a-checkout-session)
NB: You'll need a physical device to test this
❌ Old Behaviour
**Notice red clearCart button is present, and subsequent presses on apple pay fail**
Uploading ScreenRecording_07-14-2025 17-08-21_1.MP4…
✅ New Behaviour
clearCart button is not shown and pressing apple pay will reopen sheet
https://github.com/user-attachments/assets/609ec63a-583c-4847-bdef-737db996167c
---
> [!IMPORTANT]
> …
> [AC][SampleApp] Clear cart state after onComplete (avoid failed onClick)

- .github/workflows/test-workflow.yml
- .swiftformat
The [new swiftformat version](https://github.com/nicklockwood/SwiftFormat/releases) (0.57.1) included some changes that has introduced new linting errors related to redudant public access modifiers. This PR excludes that rule as we've decided to keep those modifiers.
> chore: exclude redundantPublic swiftformat rule

- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp/Views/Components/ButtonSet.swift
- Sources/ShopifyAcceleratedCheckouts/Localizable.xcstrings
- Sources/ShopifyAcceleratedCheckouts/Wallets/AcceleratedCheckoutButtons.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayButton.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/Wallet.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ApplePayIntegrationTests.swift
This PR renames wallet enum cases to camelCase to match convention.
- Rename Wallet.applepay to Wallet.applePay
- Rename Wallet.shoppay to Wallet.shopPay
- Update withWallets() modifier to wallets() for consistency
- Update all references and localization keys
> Accelerated Checkouts: rename wallet enum cases to camelCase convention

- .github/workflows/test-workflow.yml
- Samples/Samples.xcworkspace/contents.xcworkspacedata
- Samples/Samples.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp.xcodeproj/project.pbxproj
- Scripts/build_samples
I noticed that the `dev build samples` wasn't building `ShopifyAcceleratedCheckouts`
This is because it was missing from the Samples xcworkspace so xcodebuild didn't pick it up as part of the project. 
With this change we will now run the build on CI as its part of the workflow 
`dev test packages` and you should see the script finish with output prefixed with "[ShopifyAcceleratedCheckoutsApp] Touching ShopifyAcceleratedCheckoutsApp.app"
---
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of Conduct](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/COD …
> [AC][CI]: Add ShopifyAcceleratedCheckouts to Samples workspace for build script

- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate+Controller.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ErrorHandler/ErrorHandler.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegateTests.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ErrorHandler/ErrorHandlerTests.swift
The interrupt takes an optional checkoutURL which was indiscriminately overwriting the checkoutURL resulting in CSK not presenting in some interrupt scenarios
This can be easily reproduced on simulator:
- Check your device region
- Add a digital item to your cart
- Set your billing address to be a country different to your device region which has different taxes e.g. GB region, US billing address
---
> [!IMPORTANT]
>
> - [ ] I've updated …
> [AC][ApplePay]: CSK not presenting after interrupts

- Sources/ShopifyAcceleratedCheckouts/Internal/Clock.swift
- Sources/ShopifyAcceleratedCheckouts/Internal/Extensions/Task.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Internal/Extensions/TaskTests.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegateTests.swift
Tests were running slowly, all around ~7 seconds per slow test.
This turned out to be a result of the Task.retrying{} logic
To fix this I have introduced a MockClock to override the sleep function in tests.
If we were using Swift Testing we'd have utils for moving clock but that doesn't seem to exist in XCTest
`dev test packages` on main - Will take over 2 minutes - many tests will be finishing in around 7 seconds
`dev test package` on this branch - should be around ~20 seconds
---
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of …
> [CI]: Reduce `dev test packages` from 150s -> 20s

- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp/Views/Components/ButtonSet.swift
- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp/Views/Components/SkeletonButton.swift
- Sources/ShopifyAcceleratedCheckouts/Internal/Models/CheckoutIdentifier.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/AcceleratedCheckoutButtons.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/Wallet.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/AcceleratedCheckoutButtonsRenderStateTests.swift
Adds an `.onRenderStateChange` modifier to the `AcceleratedCheckoutButtons` component.
Fires an event with an enum of either `.loading`, `.fallback` or `.rendered` so consumers can render alternative UI, see `ButtonSet.swift` for how this can look.
If you change the ButtonSet.swift so that the cartID is empty string you should find that the component immediately goes to the fallback state 
```
// Cart-based checkout example with event handlers
AcceleratedCheckoutButtons(cartID: "")
```
If you set your network to be slow 3G You should see it go from loading state to rendered
https://github.com/user-attachments/assets/0fc253dd-3fa6-4248-afbe-36addc16dc4c
---
> [!IMPORTANT]
>
> - [ ] I have read and agree with the [Contribution …
> [AC][AcceleratedCheckoutButtons]: Add `onRenderStateChange` modifier

- Sources/ShopifyAcceleratedCheckouts/Internal/GraphQLClient/GraphQLDocument/GraphQLDocument+Mutations.swift
- Sources/ShopifyAcceleratedCheckouts/Internal/GraphQLClient/GraphQLRequest/GraphQLRequest+Operations.swift
- Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI+Mutations.swift
- Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI+Types.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate+Controller.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayViewController.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/Data/PKEncoder.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Internal/StorefrontAPI/StorefrontAPIMutationsTests.swift
This PR looks to tackle some flakiness / inconsistency seen both in this library and in portable-wallets when checking out digital carts with tricky tax requirements on the billing addresses.
I've tackled this in a two phase approach:
1. I've added a new mutation `cartUpdateBillingAddress` that is hidden on the storefront API and was previously unknown to us. This allows us to update with the partial billing address (during `didSelectPaymentMethod`) and complete billing address (during `didAuthorizePayment`) events. In the case of digital carts this is what is used for calculating taxes and allows us to present a correct amount prior to the user authorising the payment
2. Added a retry mechanism around the `updatePaymentMethod` mutation - this sometimes may invalidate the taxes pending …
> [AC][ApplePay]: didAuthorizePayment - cartUpdateBillingAddress on digital carts to resolve taxes 

- .gitignore
- Samples/MobileBuyIntegration/MobileBuyIntegration.xcodeproj/project.pbxproj
Fixes this build error in development, which is caused by the presence of the `.dev` folder as a result of calling `dev up`.
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTIN …
> [SampleApp] Remove .dev folder from builds

- Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI+Types.swift
Fixes issue with misconfigured `DiscountApplicationTargetType`. See https://shopify.dev/docs/api/storefront/2025-04/enums/DiscountApplicationTargetType for documentation
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing …
> Fix misconfigured SHIPPING_LINE string in Storefront API

- Samples/MobileBuyIntegration/MobileBuyIntegration/Views/ProductView.swift
Leverages the `AcceleratedCheckoutButtons(variantID, quantity)` on the `ProductView` (PDP) page.
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version …
> [Sample] Add apple pay button to PDP

- .github/workflows/test-workflow.yml
Package tests are exceeding 1 hour on some dependenabot PRs which is wasting resources. Adding a 20 min timeout.
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/.github/CONTRIBUTING.md#releasi …
> Add timeout to package tests

- Samples/ShopifyAcceleratedCheckoutsApp/ShopifyAcceleratedCheckoutsApp/Views/Components/ButtonSet.swift
- ShopifyCheckoutSheetKit.podspec
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayViewController.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ShopPay/ShopPayViewController.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutWebViewController.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewControllerTests.swift
We are currently not recovering from potentially recoverable errors being thrown by Checkout Sheet Kit in AcceleratedCheckouts
CheckoutSheetKit can also get into an infinite loop if the consumer always returns `true` in `shouldRecoverFromError` - this has been resolved with a single retry before dismissal
If you want to test you can return true on the onShouldRecover in the sample app (either one) and then in proxyman if you intercept requests to your stores cart/checkouts urls with 500's observe the logs will stop after a few retries (versus main where it persists even with a closed sheet)
---
> [!IMPORTANT]
>
> - [ ] I have read and agree with the [Contribution Guidelines](https://github.com/shopify/checkout-sheet-kit-swift/blob/main/ …
> Fix: return error.isRecoverable in shouldRecoverFromError 

- Samples/MobileBuyIntegration/MobileBuyIntegration/CartManager.swift
- Samples/MobileBuyIntegration/MobileBuyIntegration/Views/CartView.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ErrorHandler/ErrorHandler_CartSubmitForCompletion.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ErrorHandler/ErrorHandler_UserErrors.swift
- Sources/ShopifyCheckoutSheetKit/CheckoutCompletedEvent.swift
- Sources/ShopifyCheckoutSheetKit/PixelEvents.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Internal/Extensions/TaskTests.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutBridgeTests.swift
- Tests/ShopifyCheckoutSheetKitTests/CheckoutWebViewTests.swift
Deleted swiftlint:disable's where the rule no longer exists
Converted existing `swiftlint:disable` / `swiftlint:enable` combinations to just `swiftlint:disable:next` to ensure no accidental disables
---
> [!IMPORTANT]
>
>
>
> - [ ] I have bumped the version number in the [`podspec` …
> Refactor: Cleanup `swiftlint:disable` on disabled rules / use `swiftlint:disable:next` exclusively

- Scripts/xcode_run
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegateControllerTests.swift
add Github Renderer output for xcbeautify on tests (write annotations on test files)
---
> [!IMPORTANT]
>
>
>
>
> _Releasing a new major version?_
>
> - [ ] …
> [CI]: GitHub action render testoutput

- Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI+Mutations.swift
- Sources/ShopifyAcceleratedCheckouts/Internal/StorefrontAPI/StorefrontAPI.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate+Controller.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegate.swift
- Sources/ShopifyAcceleratedCheckouts/Wallets/ApplePay/Data/PKEncoder.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Internal/StorefrontAPI/StorefrontAPIMutationsTests.swift
- Tests/ShopifyAcceleratedCheckoutsTests/TestHelpers.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/ApplePayAuthorizationDelegate/ApplePayAuthorizationDelegateControllerTests.swift
- Tests/ShopifyAcceleratedCheckoutsTests/Wallets/ApplePay/PKEncoderTests.swift
Fixes: https://github.com/Shopify/checkout-sdk-issues/issues/565
UK/CA postalCodes are anonymised and can cause deliveryGroups to fail to resolve if only dynamic rates are available.
CheckoutWeb fixes this by padding the postal code with some characters so its a 'valid' postalCode
Also we were performing some `setCart`'s on results that weren't prepareForCompletion - this causes inconsistent states because only prepareForCompletion can give us pending terms - as such I've refactored each of these methods to not setCart and move prepares to immediately after
finally there is a bug with cartSelectedDeliveryOptionsUpdate where we are receiving a null cart despite the mutation being successful - I've been advised to ignore the validation there (which is why I've commented it out) and instead …
> [AC]: Pad postal codes for UK/CA postalCodes

- Sources/ShopifyAcceleratedCheckouts/Wallets/ShopPay/ShopPayButton.swift
Adds a "Shop Pay" accessibility label to the shop pay button..
```ts
await $('//XCUIElementTypeButton[@label="Shop Pay"]');
```
---
> [!IMPORTANT]
>
>
>
>
> …
> Add Shop Pay accessibility label to ShopPay button
